version: '3'

services:
    headnode:
        build: app_headnode/
        volumes:
            - ./app_headnode:/app_headnode
        command: python headnode.py
        image: ubuntu
        ports:
            - "10000:10000"
    datanode1:
        build: app_datanode/
        volumes:
            - ./app_datanode:/app_datanode
        command: python datanode.py
        depends_on:
            - headnode
    datanode2:
        build: app_datanode/
        volumes:
            - ./app_datanode:/app_datanode
        command: python datanode.py
        depends_on:
            - datanode1
    datanode3:
        build: app_datanode/
        volumes:
            - ./app_datanode:/app_datanode
        command: python datanode.py
        depends_on:
            - datanode2
    client:
        build: app_client/
        volumes:
            - ./app_client:/app_client
        command: python client.py
        depends_on:
            - datanode3
